import 'package:fleetwise/models/vehicle.dart';
import 'package:fleetwise/models/sensor_reading.dart';

class VehicleService {
  static List<Vehicle> getMockVehicles() {
    final now = DateTime.now();
    
    return [
      Vehicle(
        id: '1',
        brand: 'Toyota',
        model: 'Corolla',
        year: 2022,
        fuelType: 'Petrol',
        color: 'White',
        plateNumber: 'GA-01-AB-1234',
        deviceIds: ['DEV001', 'CAM001'],
        photoUrls: [],
        status: VehicleStatus.critical,
        lastReading: now.subtract(const Duration(minutes: 5)),
        alcoholLevel: 0.0,
        engineTemp: 85.5,
        batteryVoltage: 12.6,
        speed: 45.0,
        alcoholReadings: _generateSparklineData(0.0, 0.02, 20),
        engineTempReadings: _generateSparklineData(85.5, 5, 20),
        batteryReadings: _generateSparklineData(12.6, 0.2, 20),
        speedReadings: _generateSparklineData(45.0, 15, 20),
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
      ),
      Vehicle(
        id: '2',
        brand: 'Honda',
        model: 'City',
        year: 2023,
        fuelType: 'Petrol',
        color: 'Silver',
        plateNumber: 'GA-01-CD-5678',
        deviceIds: ['DEV002', 'CAM002'],
        photoUrls: [],
        status: VehicleStatus.warning,
        lastReading: now.subtract(const Duration(minutes: 10)),
        alcoholLevel: 0.05,
        engineTemp: 95.0,
        batteryVoltage: 11.8,
        speed: 60.0,
        alcoholReadings: _generateSparklineData(0.05, 0.03, 20),
        engineTempReadings: _generateSparklineData(95.0, 8, 20),
        batteryReadings: _generateSparklineData(11.8, 0.3, 20),
        speedReadings: _generateSparklineData(60.0, 20, 20),
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now,
      ),
      Vehicle(
        id: '3',
        brand: 'Hyundai',
        model: 'Creta',
        year: 2023,
        fuelType: 'Diesel',
        color: 'Black',
        plateNumber: 'GA-01-EF-9012',
        deviceIds: ['DEV003', 'CAM003'],
        photoUrls: [],
        status: VehicleStatus.critical,
        lastReading: now.subtract(const Duration(minutes: 2)),
        alcoholLevel: 0.12,
        engineTemp: 105.0,
        batteryVoltage: 11.2,
        speed: 80.0,
        alcoholReadings: _generateSparklineData(0.12, 0.05, 20),
        engineTempReadings: _generateSparklineData(105.0, 10, 20),
        batteryReadings: _generateSparklineData(11.2, 0.4, 20),
        speedReadings: _generateSparklineData(80.0, 25, 20),
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now,
      ),
      Vehicle(
        id: '4',
        brand: 'Maruti',
        model: 'Swift',
        year: 2021,
        fuelType: 'Petrol',
        color: 'Red',
        plateNumber: 'GA-02-GH-3456',
        deviceIds: ['DEV004', 'CAM004'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 8)),
        alcoholLevel: 0.0,
        engineTemp: 82.0,
        batteryVoltage: 12.8,
        speed: 35.0,
        alcoholReadings: _generateSparklineData(0.0, 0.01, 20),
        engineTempReadings: _generateSparklineData(82.0, 4, 20),
        batteryReadings: _generateSparklineData(12.8, 0.15, 20),
        speedReadings: _generateSparklineData(35.0, 12, 20),
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
      ),
      Vehicle(
        id: '5',
        brand: 'Mahindra',
        model: 'XUV700',
        year: 2023,
        fuelType: 'Diesel',
        color: 'Blue',
        plateNumber: 'GA-02-IJ-7890',
        deviceIds: ['DEV005', 'CAM005'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 15)),
        alcoholLevel: 0.0,
        engineTemp: 88.0,
        batteryVoltage: 12.4,
        speed: 50.0,
        alcoholReadings: _generateSparklineData(0.0, 0.015, 20),
        engineTempReadings: _generateSparklineData(88.0, 6, 20),
        batteryReadings: _generateSparklineData(12.4, 0.25, 20),
        speedReadings: _generateSparklineData(50.0, 18, 20),
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Vehicle(
        id: '6',
        brand: 'Tata',
        model: 'Nexon',
        year: 2022,
        fuelType: 'Electric',
        color: 'White',
        plateNumber: 'GA-03-KL-1122',
        deviceIds: ['DEV006', 'CAM006'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 12)),
        alcoholLevel: 0.0,
        engineTemp: 75.0,
        batteryVoltage: 13.2,
        speed: 55.0,
        alcoholReadings: _generateSparklineData(0.0, 0.01, 20),
        engineTempReadings: _generateSparklineData(75.0, 3, 20),
        batteryReadings: _generateSparklineData(13.2, 0.1, 20),
        speedReadings: _generateSparklineData(55.0, 16, 20),
        createdAt: now.subtract(const Duration(days: 35)),
        updatedAt: now,
      ),
      Vehicle(
        id: '7',
        brand: 'Kia',
        model: 'Seltos',
        year: 2023,
        fuelType: 'Petrol',
        color: 'Grey',
        plateNumber: 'GA-03-MN-3344',
        deviceIds: ['DEV007', 'CAM007'],
        photoUrls: [],
        status: VehicleStatus.warning,
        lastReading: now.subtract(const Duration(minutes: 7)),
        alcoholLevel: 0.04,
        engineTemp: 92.0,
        batteryVoltage: 12.0,
        speed: 65.0,
        alcoholReadings: _generateSparklineData(0.04, 0.025, 20),
        engineTempReadings: _generateSparklineData(92.0, 7, 20),
        batteryReadings: _generateSparklineData(12.0, 0.28, 20),
        speedReadings: _generateSparklineData(65.0, 22, 20),
        createdAt: now.subtract(const Duration(days: 10)),
        updatedAt: now,
      ),
      Vehicle(
        id: '8',
        brand: 'Volkswagen',
        model: 'Polo',
        year: 2021,
        fuelType: 'Petrol',
        color: 'Orange',
        plateNumber: 'GA-04-OP-5566',
        deviceIds: ['DEV008', 'CAM008'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 20)),
        alcoholLevel: 0.0,
        engineTemp: 84.0,
        batteryVoltage: 12.5,
        speed: 42.0,
        alcoholReadings: _generateSparklineData(0.0, 0.018, 20),
        engineTempReadings: _generateSparklineData(84.0, 5.5, 20),
        batteryReadings: _generateSparklineData(12.5, 0.22, 20),
        speedReadings: _generateSparklineData(42.0, 14, 20),
        createdAt: now.subtract(const Duration(days: 50)),
        updatedAt: now,
      ),
      Vehicle(
        id: '9',
        brand: 'Ford',
        model: 'EcoSport',
        year: 2022,
        fuelType: 'Diesel',
        color: 'Green',
        plateNumber: 'GA-04-QR-7788',
        deviceIds: ['DEV009', 'CAM009'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 18)),
        alcoholLevel: 0.0,
        engineTemp: 86.0,
        batteryVoltage: 12.7,
        speed: 48.0,
        alcoholReadings: _generateSparklineData(0.0, 0.012, 20),
        engineTempReadings: _generateSparklineData(86.0, 4.8, 20),
        batteryReadings: _generateSparklineData(12.7, 0.18, 20),
        speedReadings: _generateSparklineData(48.0, 17, 20),
        createdAt: now.subtract(const Duration(days: 28)),
        updatedAt: now,
      ),
      Vehicle(
        id: '10',
        brand: 'Nissan',
        model: 'Magnite',
        year: 2023,
        fuelType: 'Petrol',
        color: 'Yellow',
        plateNumber: 'GA-05-ST-9900',
        deviceIds: ['DEV010', 'CAM010'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 6)),
        alcoholLevel: 0.0,
        engineTemp: 83.0,
        batteryVoltage: 12.9,
        speed: 40.0,
        alcoholReadings: _generateSparklineData(0.0, 0.016, 20),
        engineTempReadings: _generateSparklineData(83.0, 4.2, 20),
        batteryReadings: _generateSparklineData(12.9, 0.12, 20),
        speedReadings: _generateSparklineData(40.0, 13, 20),
        createdAt: now.subtract(const Duration(days: 12)),
        updatedAt: now,
      ),
      Vehicle(
        id: '11',
        brand: 'Renault',
        model: 'Duster',
        year: 2021,
        fuelType: 'Diesel',
        color: 'Brown',
        plateNumber: 'GA-05-UV-2211',
        deviceIds: ['DEV011', 'CAM011'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 14)),
        alcoholLevel: 0.0,
        engineTemp: 87.0,
        batteryVoltage: 12.3,
        speed: 52.0,
        alcoholReadings: _generateSparklineData(0.0, 0.014, 20),
        engineTempReadings: _generateSparklineData(87.0, 5.8, 20),
        batteryReadings: _generateSparklineData(12.3, 0.26, 20),
        speedReadings: _generateSparklineData(52.0, 19, 20),
        createdAt: now.subtract(const Duration(days: 55)),
        updatedAt: now,
      ),
      Vehicle(
        id: '12',
        brand: 'Skoda',
        model: 'Kushaq',
        year: 2023,
        fuelType: 'Petrol',
        color: 'Purple',
        plateNumber: 'GA-06-WX-4433',
        deviceIds: ['DEV012', 'CAM012'],
        photoUrls: [],
        status: VehicleStatus.healthy,
        lastReading: now.subtract(const Duration(minutes: 9)),
        alcoholLevel: 0.0,
        engineTemp: 81.0,
        batteryVoltage: 13.0,
        speed: 38.0,
        alcoholReadings: _generateSparklineData(0.0, 0.011, 20),
        engineTempReadings: _generateSparklineData(81.0, 3.8, 20),
        batteryReadings: _generateSparklineData(13.0, 0.14, 20),
        speedReadings: _generateSparklineData(38.0, 11, 20),
        createdAt: now.subtract(const Duration(days: 8)),
        updatedAt: now,
      ),
    ];
  }

  static List<SensorReading> _generateSparklineData(double baseValue, double variance, int count) {
    final readings = <SensorReading>[];
    final now = DateTime.now();
    
    for (int i = count; i >= 0; i--) {
      final timestamp = now.subtract(Duration(minutes: i * 5));
      final value = baseValue + (variance * (0.5 - (i % 3) / 3));
      readings.add(SensorReading(timestamp: timestamp, value: value));
    }
    
    return readings;
  }

  static List<Vehicle> searchVehicles(List<Vehicle> vehicles, String query) {
    if (query.isEmpty) return vehicles;
    
    final lowerQuery = query.toLowerCase();
    return vehicles.where((v) =>
      v.plateNumber.toLowerCase().contains(lowerQuery) ||
      v.model.toLowerCase().contains(lowerQuery) ||
      v.brand.toLowerCase().contains(lowerQuery)
    ).toList();
  }
}
